### ISSUE TITLE
Wrong split character between namespace and mosaic

### ISSUE THREAD

**Issue by daoka** [44uk/nem-petit-ico#1]
https://github.com/44uk/nem-petit-ico/blob/60d05e6a9af10e682a1cc8f295e7cffa1dc28612/lib/helper.js#L100

Is the correct split character `:` ?

**Comment by 44uk** [comment]
Thanks! Fixed it https://github.com/44uk/nem-petit-ico/commit/c975c729295c7f7d33e855855f0f878697e4a184 👍
